name: avianicare
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+11

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  dotted_line: ^3.2.2
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.4.1
  shimmer: ^3.0.0
  http: ^1.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.2.0
  country_state_city_picker: ^1.2.8
  dropdown_search: ^5.0.6
  csc_picker: ^0.2.7
  country_code_picker: ^3.0.0
  fluttertoast: ^8.2.2
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.0
  printing: ^5.12.0
  flutter_html:
  youtube_player_flutter: ^8.1.2
  firebase_messaging: ^14.7.10
  firebase_core: ^2.9.0
  flutter_local_notifications: ^17.2.2
  flutter_inappwebview: ^5.7.2+3
  win32: ^5.5.3
  archive: ^3.6.1
  flutter_native_splash: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/product-details/



flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/app_icon.png"
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#479B76"
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"


flutter_native_splash:
  color: "#479B76"
  image: assets/images/logo.png
  branding: assets/images/logo.png